a = int(input())
b = int(input())
print("arithmetical operations are:")
print("a+b=",a+b)
print("a-b=",a-b)
print("a*b=",a*b)
print("a/b=",a/b)
print("a**b=",a**b)
print("a//b=",a//b)
print("a%b=",a%b)
