sno = int(input("Enter sno: "))
name = input("Enter your name: ")
gender = input("Are you male or female: ")
group = input("In which group are you studying: ")
address = input("Where do you live: ")
phn = input("How can I contact you: ")
print("The student number is",sno)
print("Your Name you entered is", name)
print("You are a",gender)
print("You are studying in",group)
print("Your address is",address)
print("Your phn number is",phn)
